### ISSUE TITLE
rake db:bootstrap_and_seed failed.

### ISSUE THREAD

**Issue by JuanitoFatas** [the-trash/open-cook#3]
Hi. I'm reporting an installation issue. I follow the instructions on README.md. At this step failed (see trace below). I use ruby 2.0.0-p247 and Rails 4. If you need more information, just tell me.

```
$ rake db:bootstrap_and_seed --trace** Invoke db:bootstrap_and_seed (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:bootstrap_and_seed
** Invoke db:bootstrap (first_time)
** Invoke environment
** Execute db:bootstrap
** Invoke db:drop (first_time)
** Invoke db:load_config (first_time)
** Execute db:load_config
** Execute db:drop
** Invoke db:create (first_time)
** Invoke db:load_config
** Execute db:create
** Invoke db:migrate (first_time)
** Invoke environment
** Invoke db:load_config
** Execute db:migrate
==  SorceryCore: migrating ====================================================
-- create_table(:users)
   -> 0.0079s
==  SorceryCore: migrated (0.0080s) ===========================================

==  SorceryRememberMe: migrating ==============================================
-- add_column(:users, :remember_me_token, :string, {:default=>nil})
   -> 0.0010s
-- add_column(:users, :remember_me_token_expires_at, :datetime, {:default=>nil})
   -> 0.0005s
-- add_index(:users, :remember_me_token)
   -> 0.0005s
==  SorceryRememberMe: migrated (0.0022s) =====================================

==  SorceryResetPassword: migrating ===========================================
-- add_column(:users, :reset_password_token, :string, {:default=>nil})
   -> 0.0008s
-- add_column(:users, :reset_password_token_expires_at, :datetime, {:default=>nil})
   -> 0.0004s
-- add_column(:users, :reset_password_email_sent_at, :datetime, {:default=>nil})
   -> 0.0005s
-- add_index(:users, :reset_password_token)
   -> 0.0023s
==  SorceryResetPassword: migrated (0.0044s) ==================================

==  CreateRoles: migrating ====================================================
-- create_table(:roles)
   -> 0.0012s
==  CreateRoles: migrated (0.0013s) ===========================================

==  CreatePublications: migrating =============================================
-- create_table(:pages)
   -> 0.0018s
-- create_table(:posts)
   -> 0.0015s
-- create_table(:hubs)
   -> 0.0021s
==  CreatePublications: migrated (0.0059s) ====================================

==  ChangeHubs: migrating =====================================================
-- change_table(:hubs)
   -> 0.0021s
==  ChangeHubs: migrated (0.0022s) ============================================

==  NestedSetFields: migrating ================================================
-- change_table(:pages)
   -> 0.0023s
-- change_table(:posts)
   -> 0.0034s
-- change_table(:hubs)
   -> 0.0021s
==  NestedSetFields: migrated (0.0080s) =======================================

==  BaseExtFields: migrating ==================================================
-- change_table(:pages)
   -> 0.0039s
-- change_table(:posts)
   -> 0.0032s
-- change_table(:hubs)
   -> 0.0042s
==  BaseExtFields: migrated (0.0118s) =========================================

==  SlugIds: migrating ========================================================
-- change_table(:pages)
   -> 0.0019s
-- change_table(:posts)
   -> 0.0012s
-- change_table(:hubs)
   -> 0.0013s
==  SlugIds: migrated (0.0046s) ===============================================

==  CreateAudits: migrating ===================================================
-- create_table(:audits)
   -> 0.0016s
==  CreateAudits: migrated (0.0025s) ==========================================

==  CreateComments: migrating =================================================
-- create_table(:comments)
   -> 0.0029s
-- create_table(:ip_black_lists)
   -> 0.0008s
-- create_table(:user_agent_black_lists)
   -> 0.0008s
-- change_table(:users)
   -> 0.0040s
-- change_table(:users)
   -> 0.0014s
-- change_table(:posts)
   -> 0.0014s
-- change_table(:pages)
   -> 0.0014s
-- change_table(:hubs)
   -> 0.0014s
==  CreateComments: migrated (0.0145s) ========================================

==  AttachedFiles: migrating ==================================================
-- create_table(:attached_files)
   -> 0.0017s
==  AttachedFiles: migrated (0.0018s) =========================================

==  ChangeStorages: migrating =================================================
-- change_table(:users)
   -> 0.0015s
-- change_table(:users)
   -> 0.0015s
-- change_table(:posts)
   -> 0.0014s
-- change_table(:pages)
   -> 0.0012s
-- change_table(:hubs)
   -> 0.0010s
==  ChangeStorages: migrated (0.0072s) ========================================

==  CreateDelayedJobs: migrating ==============================================
-- create_table(:delayed_jobs, {:force=>true})
   -> 0.0016s
-- add_index(:delayed_jobs, [:priority, :run_at], {:name=>"delayed_jobs_priority"})
   -> 0.0005s
==  CreateDelayedJobs: migrated (0.0023s) =====================================

==  ActsAsTaggableOnMigration: migrating ======================================
-- create_table(:tags)
   -> 0.0011s
-- create_table(:taggings)
   -> 0.0009s
-- add_index(:taggings, :tag_id)
   -> 0.0021s
-- add_index(:taggings, [:taggable_id, :taggable_type, :context])
   -> 0.0013s
==  ActsAsTaggableOnMigration: migrated (0.0058s) =============================

** Invoke db:_dump (first_time)
** Execute db:_dump
** Invoke db:schema:dump (first_time)
** Invoke environment
** Invoke db:load_config
** Execute db:schema:dump
** Invoke db:seed (first_time)
** Invoke db:seed:common (first_time)
** Invoke db:seed:original (first_time)
** Invoke db:abort_if_pending_migrations (first_time)
** Invoke environment
** Execute db:abort_if_pending_migrations
** Execute db:seed:original
"base of seeds"
** Execute db:seed:common
** Invoke db:seed:development (first_time)
** Invoke db:seed:common
** Invoke db:seed:development:clean (first_time)
** Invoke db:abort_if_pending_migrations
** Execute db:seed:development:clean
DB is clean
** Invoke db:seed:development:comments (first_time)
** Invoke db:abort_if_pending_migrations
** Execute db:seed:development:comments
** Invoke db:seed:development:comments:body (first_time)
** Invoke db:seed:development:pages (first_time)
** Invoke db:abort_if_pending_migrations
** Execute db:seed:development:pages
** Invoke db:seed:development:pages:body (first_time)
** Invoke db:seed:development:pages_hubs (first_time)
** Invoke db:abort_if_pending_migrations
** Execute db:seed:development:pages_hubs
** Invoke db:seed:development:pages_hubs:body (first_time)
** Invoke db:seed:development:posts (first_time)
** Invoke db:abort_if_pending_migrations
** Execute db:seed:development:posts
** Invoke db:seed:development:posts:body (first_time)
** Invoke db:seed:development:recipes (first_time)
** Invoke db:abort_if_pending_migrations
** Execute db:seed:development:recipes
** Invoke db:seed:development:recipes:body (first_time)
** Invoke db:seed:development:recipes_hubs (first_time)
** Invoke db:abort_if_pending_migrations
** Execute db:seed:development:recipes_hubs
** Invoke db:seed:development:recipes_hubs:body (first_time)
** Invoke db:seed:development:hubs (first_time)
** Invoke db:abort_if_pending_migrations
** Execute db:seed:development:hubs
** Invoke db:seed:development:hubs:body (first_time)
** Invoke db:seed:development:users (first_time)
** Invoke db:abort_if_pending_migrations
** Execute db:seed:development:users
** Invoke db:seed:development:users:body (first_time)
** Invoke db:seed:development:roles (first_time)
** Invoke db:abort_if_pending_migrations
** Execute db:seed:development:roles
** Invoke db:seed:development:roles:body (first_time)
** Invoke db:seed:development:clean
** Execute db:seed:development:roles:body
Roles created
** Execute db:seed:development:users:body
User 1 role:author created
User 2 role:author created
User 3 role:blogger created
User 4 role:author created
User 5 role:blogger created
User 6 role:blogger created
User 7 role:author created
User 8 role:blogger created
User 9 role:blogger created
User 10 role:author created
Admin set
** Execute db:seed:development:hubs:body
Hubs created
** Execute db:seed:development:recipes_hubs:body
.....................
Recipe hubs created
** Execute db:seed:development:recipes:body
....................................................................................
Recipes created
** Execute db:seed:development:posts:body
 --- blogs
.........
 --- videos
.........
 --- articles
.........
 --- interviews
.........
Posts created
** Execute db:seed:development:pages_hubs:body

Pages hubs created
** Execute db:seed:development:pages:body
rake aborted!
undefined method `root_hub' for nil:NilClass
/Users/Mac/dev/rails4/open-cook/app/models/concerns/base_publication.rb:30:in `root_hub'
/Users/Mac/dev/rails4/open-cook/app/models/concerns/base_publication.rb:70:in `prepare_content'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:427:in `_run__3024858226452580173__save__callbacks'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:80:in `run_callbacks'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/callbacks.rb:299:in `create_or_update'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/persistence.rb:128:in `save!'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/validations.rb:57:in `save!'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/attribute_methods/dirty.rb:41:in `save!'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/transactions.rb:275:in `block in save!'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/transactions.rb:326:in `block in with_transaction_returning_status'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:200:in `transaction'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/transactions.rb:209:in `transaction'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/transactions.rb:323:in `with_transaction_returning_status'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/transactions.rb:275:in `save!'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/state_machine-1.2.0/lib/state_machine/integrations/active_record.rb:487:in `block in save!'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/state_machine-1.2.0/lib/state_machine/integrations/active_record.rb:502:in `block (2 levels) in around_save'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:150:in `block in run_actions'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:170:in `catch_exceptions'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:148:in `run_actions'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:133:in `run_callbacks'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:212:in `run_callbacks'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:63:in `block (2 levels) in perform'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:63:in `catch'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:63:in `block in perform'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:186:in `within_transaction'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/state_machine-1.2.0/lib/state_machine/transition_collection.rb:62:in `perform'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/state_machine-1.2.0/lib/state_machine/integrations/active_record.rb:502:in `block in around_save'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/state_machine-1.2.0/lib/state_machine/integrations/active_record.rb:530:in `block in transaction'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:200:in `transaction'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/transactions.rb:209:in `transaction'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/state_machine-1.2.0/lib/state_machine/integrations/active_record.rb:529:in `transaction'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/state_machine-1.2.0/lib/state_machine/integrations/active_record.rb:501:in `around_save'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/state_machine-1.2.0/lib/state_machine/integrations/active_record.rb:487:in `save!'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/associations/has_many_association.rb:37:in `insert_record'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/associations/collection_association.rb:463:in `block (2 levels) in create_record'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/associations/collection_association.rb:367:in `add_to_target'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/associations/collection_association.rb:461:in `block in create_record'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/associations/collection_association.rb:152:in `block in transaction'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:202:in `block in transaction'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:210:in `within_new_transaction'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:202:in `transaction'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/transactions.rb:209:in `transaction'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/associations/collection_association.rb:151:in `transaction'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/associations/collection_association.rb:460:in `create_record'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/associations/collection_association.rb:125:in `create!'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/activerecord-4.0.0/lib/active_record/associations/collection_proxy.rb:276:in `create!'
/Users/Mac/dev/rails4/open-cook/db/seeds/development/pages.seeds.rb:10:in `block (2 levels) in define_seed_task'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/task.rb:236:in `call'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/task.rb:236:in `block in execute'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/task.rb:231:in `each'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/task.rb:231:in `execute'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/task.rb:175:in `block in invoke_with_call_chain'
/Users/Mac/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/task.rb:168:in `invoke_with_call_chain'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/task.rb:161:in `invoke'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/bundler/gems/seedbank-c7a272751336/lib/seedbank/runner.rb:27:in `after'
/Users/Mac/dev/rails4/open-cook/db/seeds/development/pages.seeds.rb:2:in `block in define_seed_task'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/bundler/gems/seedbank-c7a272751336/lib/seedbank/dsl.rb:24:in `module_eval'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/bundler/gems/seedbank-c7a272751336/lib/seedbank/dsl.rb:24:in `block in define_seed_task'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/task.rb:234:in `call'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/task.rb:234:in `block in execute'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/task.rb:231:in `each'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/task.rb:231:in `execute'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/task.rb:175:in `block in invoke_with_call_chain'
/Users/Mac/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/task.rb:168:in `invoke_with_call_chain'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/task.rb:197:in `block in invoke_prerequisites'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/task.rb:195:in `each'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/task.rb:195:in `invoke_prerequisites'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/task.rb:174:in `block in invoke_with_call_chain'
/Users/Mac/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/task.rb:168:in `invoke_with_call_chain'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/task.rb:161:in `invoke'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/bundler/gems/seedbank-c7a272751336/lib/seedbank/runner.rb:27:in `after'
/Users/Mac/dev/rails4/open-cook/db/seeds/development/comments.seeds.rb:29:in `block in define_seed_task'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/bundler/gems/seedbank-c7a272751336/lib/seedbank/dsl.rb:24:in `module_eval'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/bundler/gems/seedbank-c7a272751336/lib/seedbank/dsl.rb:24:in `block in define_seed_task'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/task.rb:234:in `call'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/task.rb:234:in `block in execute'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/task.rb:231:in `each'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/task.rb:231:in `execute'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/task.rb:175:in `block in invoke_with_call_chain'
/Users/Mac/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/task.rb:168:in `invoke_with_call_chain'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/task.rb:197:in `block in invoke_prerequisites'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/task.rb:195:in `each'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/task.rb:195:in `invoke_prerequisites'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/task.rb:174:in `block in invoke_with_call_chain'
/Users/Mac/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/task.rb:168:in `invoke_with_call_chain'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/task.rb:197:in `block in invoke_prerequisites'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/task.rb:195:in `each'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/task.rb:195:in `invoke_prerequisites'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/task.rb:174:in `block in invoke_with_call_chain'
/Users/Mac/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/task.rb:168:in `invoke_with_call_chain'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/task.rb:161:in `invoke'
/Users/Mac/dev/rails4/open-cook/lib/tasks/db_bootstrap.rake:14:in `block (2 levels) in <top (required)>'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/task.rb:236:in `call'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/task.rb:236:in `block in execute'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/task.rb:231:in `each'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/task.rb:231:in `execute'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/task.rb:175:in `block in invoke_with_call_chain'
/Users/Mac/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/task.rb:168:in `invoke_with_call_chain'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/task.rb:161:in `invoke'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/application.rb:149:in `invoke_task'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/application.rb:106:in `each'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/application.rb:106:in `block in top_level'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/application.rb:115:in `run_with_threads'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/application.rb:100:in `top_level'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/application.rb:78:in `block in run'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/application.rb:165:in `standard_exception_handling'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/lib/rake/application.rb:75:in `run'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/gems/rake-10.1.0/bin/rake:33:in `<top (required)>'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/bin/rake:23:in `load'
/Users/Mac/.rvm/gems/ruby-2.0.0-p247@rails4/bin/rake:23:in `<main>'
Tasks: TOP => db:seed:development:pages:body
```

**Comment by the-teacher** [comment]
I'll check it tomorrow

But you should be ready - it's prototype of my tasty CMS. I need a lot of time for release

**Comment by JuanitoFatas** [comment]
Don´t worry! I´m not pushing you. I understand this is a prototype. Thank you for such a great project. I´m learning from your code base. :smile:

**Comment by the-teacher** [comment]
;)

open-cook is blog-oriented CMS for my personal food-blogging project. I make it with love and without hurry
I play with code and implement my personal view on CMS architecture.
Maybe it's not good, but I like it - and it's make me happy
I plan to release this project at end of this year - And maybe it's will be new WordPress :)

**Comment by JuanitoFatas** [comment]
I will keep an eye on it. And see if I could contribute some code into it, of course, with love. : ) You made bunch of awesome stuff. Keep going man. :+1: :+1: :+1:

**Comment by the-teacher** [comment]
Wow )) 17 days ago! Sorry for your waiting. Current commit should works fine! ))
